name: Tests

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  tests:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-requirements-${{ hashFiles('requirements/*.txt') }}
          restore-keys: |
            ${{ runner.os }}-requirements-
      - name: Install test packages, download nltk corpora and install requirements.txt versions
        run: |
          pip install -r requirements/test.txt
          python setup.py install
      - run: coverage run -m pytest
      - uses: codecov/codecov-action@v1
